server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dva?useUnicode=true&characterEncoding=utf8
        username: root
        password: